### ISSUE TITLE
OAS document divergences

### ISSUE THREAD

**Issue by jshepherd01** [AR-Reshare/AR-Reshare#50]
The OAS document diverges from the actual implementation of pipelines in a few areas. See #48 and #49 for specifics.

Additionally, the status codes shown in the document may not be accurate to the ones returnable by the pipelines. In particular, many scenarios which should, by the docs, return 403 (forbidden) actually return 404 (not found). This was done to improve security, as a user will have no way of distinguishing between an entity they have no access to and an entity which does not exist.

**Comment by zshepherd01** [comment]
I'll try to enumerate them all here:

general
- IDs are integers, not strings
- media uploads are passed as strings of the form `"data:image/type;base64,<file encoded into base64 format>`
- all error responses take the same form. It might be best to just have a single "error-response" schema to attach to every error state

/categories/list
- the response is an object with a key "categories" that contains the array
- categoryName is not enumerated
- categoryPath is replaced with parentCategoryID, which contains only the categoryID of the immediate parent
- colour is spelt with a u. It might also be worth mentioning that it's rgba

/account/create
- a "picture" key is added for the profile picture (image only)

/account/login
- ~~the token is called "deviceToken", not "registrationToken"~~

/account/modify
- the request object is "flattened", and should contain: password, name, email, newPassword, dob, picture. Only the first is required

/account/listing/view
- the media objects should contain "mimetype" and "url", instead of "media" and "description"
- the location object should be removed, and "country", "region", and "postcode" added directly instead

/account/listings/search
- currently listed as 501, but we have implemented it

/account/addresses/list
- The response is an object with a key "addresses" that contains the array
- The country, region, and postcode should be added directly to the list elements, rather than being inside a separate "address" object

/listing/view
- Has the same problems with media and location that /account/listing/view does

/listings/search
- "max" and "start" should be "maxResults" and "startResults"
- "categoryId" should be spelt with uppercase "D"
- The response is an object with a key "listings" that contains the array
- The array elements have the same location and media issues as /listing/view
- Each array element should also have a "description" field

/listing/create
- Something weird is going on with the request body, which has a dropdown option with it
- "country", "region", and "postcode" are here twice. They should be in the "location" object
- "location" may also be the ID of an address
- "media" should be an array of strings
- The response object should contain the listingID in the "success" field

/listing/modify
- Again, the location can be either an object or the ID of an address
- A "media" field should be added
- The "variable-modification" object should be flattened as with /account/modify

/conversation/message
- "receiverID" should be removed from the request body
- "mediaContent", which can be a single image or video, should be added

Getting paranoid about how long I haven't saved for so I'll do the rest in a new comment

**Comment by user5423** [comment]
I've opened up oas-dev branch to address these issues

**Comment by zshepherd01** [comment]
/listing/search
- authentication is optional, and behaviour changes if it is provided

This is only an issue if the fix to #59 is accepted

**Comment by zshepherd01** [comment]
We'll also have to figure out which values are allowed to be "null"
